version: 0.2

env:
  shell: bash
  variables:
    ACCOUNTID: "991663395193"
    name: "terraform"


phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - source .env
      - aws ecr get-login-password --region $AWS_REGION
  build:
    commands:
      - echo Build started on `date`

      - docker build -t $image:$version -t $ecr_image:$version .
      - docker tag $ecr_image:$version $ecr_image:$CODEBUILD_BUILD_NUMBER
      - docker tag $ecr_image:$version $ecr_image:latest
  post_build:
    commands:
      - docker login --username AWS --password-stdin $ACCOUNTID.dkr.ecr.$AWS_REGION.amazonaws.com/$name
      - docker push $ecr_image:$CODEBUILD_BUILD_NUMBER
      - docker push $ecr_image:latest
      - echo Build completed on `date`