version: 0.2

env:
  shell: bash
  privileged-mode: true
  variables:
    ACCOUNT_ID: "991663395193"

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - source .env
      - aws ecr get-login-password --region $AWS_REGION
  build:
    commands:
      - echo Build started on `date`

      - docker build -t $IMAGE:$VERSION -t $ECR_IMAGE:$VERSION .
      - docker tag $ECR_IMAGE:$VERSION $ECR_IMAGE:$CODEBUILD_BUILD_NUMBER
      - docker tag $ECR_IMAGE:$VERSION $ECR_IMAGE:latest
  post_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$name
      - docker push $ECR_IMAGE:$CODEBUILD_BUILD_NUMBER
      - docker push $ECR_IMAGE:latest
      - echo Build completed on `date`