version: 0.2

env:
  variables:
    ACCOUNTID: "991663395193"
    name: "terraform"


phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - export REGION=$AWS_REGION
      - export REPO=${ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com
      - export GIT_SHA=$(git rev-parse HEAD 2>/dev/null | cut -c 1-7)
      - export version="${GIT_SHA}"

      - export image="${image:-$REPO/$name}"
      - export ecr_image="${REPO}/${name}"

      - docker build -t $image:$version -t $ecr_image:$version .

      - docker tag $image:$version $image:$CODEBUILD_BUILD_NUMBER
      - docker tag $image:$version $image:latest
      - docker tag $ecr_image:$version $ecr_image:$CODEBUILD_BUILD_NUMBER
      - docker tag $ecr_image:$version $ecr_image:latest
  post_build:
    commands:
      - echo Build completed on `date`