version: 0.2

env:
  variables:
    ACCOUNTID: "991663395193"
    name: "terraform"


phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - source .env

      - docker build -t $image:$version -t $ecr_image:$version .

      - docker tag $image:$version $image:$CODEBUILD_BUILD_NUMBER
      - docker tag $image:$version $image:latest
      - docker tag $ecr_image:$version $ecr_image:$CODEBUILD_BUILD_NUMBER
      - docker tag $ecr_image:$version $ecr_image:latest
  post_build:
    commands:
      - echo Build completed on `date`